# Generated by Django 4.2.5 on 2023-09-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltacademy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=200),
        ),
    ]
