# Generated by Django 4.2.5 on 2023-09-12 03:47

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_mathquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathquestion',
            name='id',
        ),
        migrations.AddField(
            model_name='mathquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathquestion',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mathquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
