# Generated by Django 4.2.5 on 2023-09-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_mathquestion_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathquestion',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='math_questions', to='home.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathquestion',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
